//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\ama\source\repos\EjemploReceta\Receta.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RecetaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IRecetaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] RecetaParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.receta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceta([NotNull] RecetaParser.RecetaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.nombre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNombre([NotNull] RecetaParser.NombreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.porciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPorciones([NotNull] RecetaParser.PorcionesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.tiempoPreparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTiempoPreparacion([NotNull] RecetaParser.TiempoPreparacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.tiempoCoccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTiempoCoccion([NotNull] RecetaParser.TiempoCoccionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.calorias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalorias([NotNull] RecetaParser.CaloriasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.ingredientes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIngredientes([NotNull] RecetaParser.IngredientesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.det_ingredientes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDet_ingredientes([NotNull] RecetaParser.Det_ingredientesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.elaboracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElaboracion([NotNull] RecetaParser.ElaboracionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetaParser.det_elaboracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDet_elaboracion([NotNull] RecetaParser.Det_elaboracionContext context);
}
